services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: omie_sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=My#Stron8P4ssw0rd
      - MSSQL_PID=Express  # Use 'Express' for free edition, or 'Developer' for development
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data: